- .github/workflows/slack-action.yml
> ✨ feat: slack action 메세지 추가

- .github/workflows/CI.yml
* push를 listen하도록 변경 (skip ci를 위해서)
* CI를 Skip할 수 있는 기능 추가(커밋 메세지에 [skip ci] 추가)
* 커밋 변경 이력을 모두 불러와 검사하도록 수정
* 설치할 Node version 명시
* Zero-Installs 관련 옵션 추가
> feat : CI 스크립트에서 빠진 스크립트를 추가하고, CI를 Skip할 수 있는 기능 추가

- .github/workflows/dependabot.yml
auto merge enable 자동화를 action으로 임시 처리해둡니다.
추후 다른 방법 서칭 후 변경 가능성이 있습니다.
기능 : update branch + auto merge
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat: auto merge enable yaml로 임시 처리

- .github/workflows/CI.yml
- devops/commandline/src/commands/CheckPackageCommitCommand.ts
> fix: 기본 CI에서 CI의 스킵 기능을 제외합니다.

- packages/ds/src/index.ts
> fix(@depromeet/ds): 패키지 배포 테스트

- .github/workflows/dependabot.yml
- .github/workflows/packagePublish.yml
> feat: dependabot CI 변경 및 protected branch push token 변경

- .github/workflows/dependabot.yml
- packages/ds/src/index.ts
> fix(@depromeet/ds): 패키지 배포 테스트 및 dependabot yaml 문법 수정

- .github/workflows/packagePublish.yml
> feat: npm에 package public으로 배포하도록 변경

- packages/ds/src/index.ts
> fix(@depromeet/ds): 배포 테스트 3

- .github/.gitmessage
> :package: chore: add gitmoji

- _templates/service/new/next.config.js.ejs.t
- next.config.js의 설정이 13버전으로 남아있어서 quiz서비스의 next.config.js의 설정과 같이 12버전으로 동기화했습니다
- 빌드 후 실행에 문제없는지 체크하였습니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(next.config.js template): 13버전으로 되어있었던 것을 12버전으로 변경

- .pnp.cjs
- packages/colors/.eslintrc.js
- packages/colors/.npmignore
- packages/colors/.vscode/settings.json
- packages/colors/package.json
- packages/colors/src/colors.ts
- packages/colors/src/emotion.d.ts
- packages/colors/src/index.ts
- packages/colors/src/shadows.ts
- packages/colors/src/theme.ts
- packages/colors/tsconfig.esm.json
- packages/colors/tsconfig.json
- packages/colors/tsconfig.typecheck.json
- yarn.lock
- 디자인토큰 정의
- 디자인 레퍼런스: 
- 관련 슬랙 링크: 
- emotion typesafe 보고있는데 잘안되네용
> feat(@depromeet/colors): colors package 

- admin.toks.com/next.config.js
경로가 잘못되어 수정합니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> fix(admin.toks.com): next config 수정

- admin.toks.com/src/pages/components/ServiceList.tsx
- admin.toks.com/src/pages/remotes/deploy.ts
build server에서 현재 빌드가 가능한 상황인지 판단하고, button disabled를 결정합니다.
이로써, 중복 배포 요청을 막습니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(admin.toks.com): build server에서 현재 빌드가 가능한 상황인지 판단하고, 배포 요청을 하도록 변경

- shared/toks-components/src/components/Txt/index.tsx
- shared/toks-components/src/components/index.ts
typo를 정의하지 않고, 우선 임시로 개발해둡니다.
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/toks-component): Txt 컴포넌트 임시 개발

- services/home/src/pages/MyStudies/index.tsx
- shared/toks-components/src/components/Button/index.tsx
- shared/toks-components/src/components/Tag/index.tsx
- shared/toks-components/src/components/index.ts
위 이미지 컴포넌트입니다.
짜치는 퍼블리싱 만나면, 시간이 지연될거 같아, 우선은 inlineStyle 적용합니다. 추후 한번에 걷어낼 예정입니다. 
사용예시
```typescript
<Tag.Row>
<Tag value="javascript" color="highlight" />
<Tag value="javascript" color="highlight" />
<Tag value="javascript" color="highlight" />
<Tag value="javascript" color="highlight" />
<Tag value="javascript" color="highlight" />
<Tag value="javascript" color="highlight" />
</Tag.Row>
```
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@shared/toks-components): Tag 컴포넌트 / Tag Row component 개발

- shared/toks-components/src/components/ToksHeader/ProfileButton/constants.ts
- shared/toks-components/src/components/ToksHeader/ProfileButton/style.ts
- shared/toks-components/src/components/ToksHeader/constants.ts
- shared/toks-components/src/components/ToksHeader/index.tsx
- shared/toks-components/src/components/ToksHeader/style.ts
피그마와 값이 다른 부분이 보여 수정합니다.
두현님 혹시 맞게 설정된건지 확인 가능할까요?
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/toks-components): header 디자인 사이즈와 다른 부분 수정

- services/home/pages/_app.tsx
- services/home/src/constants/queryKeys.ts
- services/home/src/pages/MyStudies/components/StudyCard/index.tsx
- services/home/src/pages/MyStudies/components/StudyList/index.tsx
- services/home/src/pages/MyStudies/index.tsx
- services/home/src/pages/MyStudies/models/study.ts
- services/home/src/pages/MyStudies/remotes/study.ts
- shared/toks-components/src/components/Tag/index.tsx
위 화면을 구성했습니다. 변경된 디자인도 반영했습니다
Tag의 경우, 눈으로 확인해보니 ellipsis되는게 별로여서, 길이만큼 그려주도록 수정했습니다.
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(home, @depromeet/toks-components): 내 스터디 리스트 확인 페이지

- shared/toks-components/src/components/Text/token.ts
- 페이지 만들다가 typo 크기 변경되어있는거 반영하면 좋을 것 같아서 반영했습니다.
> feat(@shared/toks-components): typo 크기 변경사항 수정

- .pnp.cjs
- services/onboarding/package.json
- services/onboarding/src/pages/Intro/components/Banner/index.tsx
- services/onboarding/src/pages/Intro/index.tsx
- services/onboarding/src/pages/Intro/style.ts
- yarn.lock
- header 추후 리팩토링 후에 추가 할 예정입니다 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(onboarding): 온보딩 페이지 구현

- packages/http/src/http.ts
1. ssr환경에서는 window가 없으므로 ssr환경 대응
2. instance -> http로 import해서 쓰도록 변경
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/http): http package 에러 수정

- serviceMap.json
- services/home/pages/_app.tsx
- services/home/src/constants/queryKeys.ts
- services/home/src/pages/MyStudies/components/StudyCard/index.tsx
- services/home/src/pages/MyStudies/components/StudyList/index.tsx
- services/home/src/pages/MyStudies/remotes/study.ts
- shared/path/src/index.ts
- shared/toks-components/src/components/TextBallon/index.tsx
- shared/toks-components/src/components/index.ts
1. my study 페이지 마무리 (말풍선 기능 추가, 변경된 디자인 반영, click event handler 등)
2. 각 서비스별로 basePath를 가지고 있어서 router로 이동시 basePath 물고 가는 현상 발생 -> 외부 서비스 이동시 사용할 유틸 구현
3. TextBallon 컴포넌트 구현
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(home, @depromeet/path, @depromeet/toks-components): my study 페이지 마무리 / TextBallon Component / routing util 개발

- .github/workflows/packagePublish.yml
- .gitmodules
> fix: git submodule 꼬인것 해결

- packages/http/package.json
- packages/http/src/http.ts
1. 타입 개선
2. 추후 쿠키사용 대비한 옵션 추가
3. {data} = axios.get() 에서 {data}가 아니라 바로 값을 받을 수 있도록 변경
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/http): http 타입 개선 및 일부 옵션 추가

- packages/http/package.json
- packages/http/src/http.ts
http에 오류가 있어서 수정합니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/http): http 오류 수정

- shared/toks-components/src/index.ts
- shared/toks-components/src/types/index.ts
- shared/toks-components/src/types/study.ts
> feat(@depromeet/toks-components): 공통 타입 폴터 정의 및 스터디 정의

- shared/toks-components/src/types/quiz.ts
- shared/toks-components/src/types/study.ts
- shared/toks-components/src/types/user.ts
- 공통으로 사용될 여지가 많은 두개의 타입을 공통으로 분리하였습니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크: 
0_<
> feat(@depromeet/toks-components): 퀴즈 타입과 유저타입을 공통 타입으로 분리

- .pnp.cjs
- packages/http/src/http.ts
- services/home/package.json
- services/home/src/pages/MyStudies/components/StudyCard/index.tsx
- services/home/src/pages/MyStudies/components/StudyList/index.tsx
- services/home/src/pages/MyStudies/models/study.ts
- services/home/src/pages/MyStudies/remotes/study.ts
- yarn.lock
> feat(@depromeet/http, home): 스터디 조회 API 연결 및 http interceptor 변경

- packages/http/package.json
- packages/http/src/http.ts
> feat(@depromeet/http): http 인증 에러 처리 변경 및 일부 config 설정 변경

- packages/http/package.json
- packages/http/src/http.ts
이미 로그인 페이지인 경우 redirect 안하도록 처리합니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/http): http - 로그인 페이지인 경우 redirect 안하도록 처리

- .pnp.cjs
- services/login/src/pages/Intro/index.tsx
- shared/toks-components/src/components/Timer/index.tsx
- shared/toks-components/src/components/index.ts
- shared/utils/.eslintrc.js
- shared/utils/package.json
- shared/utils/src/hooks/useTimer.tsx
- shared/utils/src/index.ts
- shared/utils/tsconfig.json
- shared/utils/tsconfig.typecheck.json
- yarn.lock
인자로는 셀 시간인, time을 받습니다. (초단위)
enabled로 타이머 동작을 제어합니다.
time: 현재 남은 시간 값 (초단위)
start: 시작
restart: 재시작
stop: 정지
duration(days, minutes, hours, seconds ... etc) : 각 시간 종류에 대한 남은 시간값
사용 예시로 Timer 컴포넌트를 만들어보았습니다.
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/utils, @depromeet/toks-components): 타이머 훅 및 예시 타이머 컴포넌트

- services/onboarding/src/pages/CreateStudy/components/CreateStudyForm/index.tsx
- services/onboarding/src/pages/CreateStudy/components/CreateStudyForm/type.ts
- shared/toks-components/src/components/Calendar/index.tsx
- shared/toks-components/src/components/DropDown/index.tsx
- shared/toks-components/src/components/Editor/Editor.tsx
- shared/toks-components/src/components/Input/index.tsx
- 디자인 레퍼런스: 
- 관련 슬랙 링크: 
- 잠수함 패치한 인풋 라벨 값 바꿨습니다.
- 변경 된 필드 값도 적용했습니다.
> feat(@depromeet/layout, onboarding): 스터디 생성 API 필드 변경 및 label variants 변경

- scripts/deploy.sh
1. 배포 스크립트 재설정
2. http 해더 설정 수정
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/http, scripts): 배포 스크립트 재설정 및 http 해더 설정 수정

- packages/http/src/http.ts
http 헤더 설정 수정 -> common 헤더 설정 전에도 바로 토큰 헤더에 담을수 있도록 수정합니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat: http 헤더 설정 수정

- packages/http/src/auth.ts
- packages/http/src/http.ts
- packages/http/src/index.ts
- shared/layout/src/components/Layout.tsx
- shared/layout/src/remote/logout.ts
로그아웃 로직 마무리입니다.
프론트에서 관리하는 토큰 파괴 + 리다이렉트
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/http, @depromeet/layout): 로그아웃 로직 마무리

- shared/layout/src/components/Layout.tsx
로그아웃 후에, 모달이 닫히고 새로 user API를 통해 정보 가져오도록 수정
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@shared/layout): 로그아웃 후에, 모달이 닫히고 새로 user API를 통해 정보 가져오도록 수정

- packages/http/src/http.ts
- services/home/src/pages/MyStudies/components/StudyCard/index.tsx
- services/home/src/pages/MyStudies/components/StudyList/index.tsx
- services/home/src/pages/MyStudies/models/study.ts
- shared/toks-components/src/components/Tag/index.tsx
1. http 토큰 파괴 로직 수정 
2. study 조회 API 변경 반영 
3. study 조회디자인 변경 반영
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/http, home): http 토큰 파괴 로직 수정 / study 조회 API 변경 반영 / 디자인 변경 반영

- services/quiz/src/pages/QuizVotingPage/components/PeerAnswerViewer/index.tsx
- services/quiz/src/pages/StudyDetailPage/components/QuizItem/index.tsx
- shared/toks-components/src/components/Accordion/index.tsx
- shared/toks-components/src/components/Accordion/style.ts
- 민석님이 말씀해 주신대로 React.CSSProperties 타입의 accordionStyle 속성을 받을 수 있게 추가하였습니다!
- 채림님 화면에서 아코디언이 발작?일으키는 증상이 있어서 details와 summary를 없애고 div태그로 변경하였습니다
- details를 사용하지 않았기 때문에 접기, 펴기 기능을 사용하려면 onFold 함수를 필수로 넣어야 합니다
- isFold가 true일때 문자 그대로 접혀야 하는데 펼치게 해놔서…. 이것도 수정했습니다… ㅎㅎ
- 디자인 레퍼런스: 
- 관련 슬랙 링크: 
🙇‍♀️
> refactor(@depromeet/toks-components): 아코디언 오류 수정 및 accordionStyle 속성 추가

- services/quiz/src/pages/StudyDetailPage/components/QuizItem/index.tsx
- services/quiz/src/pages/StudyDetailPage/components/QuizList/index.tsx
- services/quiz/src/pages/StudyDetailPage/components/StudyInfo/index.tsx
- shared/toks-components/src/components/BackButton/style.ts
- 현재 서버에 진행 중인 퀴즈 데이터가 없어서 확인은 못했지만 퀴즈 풀기 이동 구현했습니다
- 퀴즈 만들기, 확인하기 이동 구현했습니다
- 추후 path부분을 개선해야 합니다.
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): router로 페이지 이동 구현

- services/login/src/pages/Intro/components/Banner/index.tsx
- services/login/src/pages/Intro/index.tsx
- services/login/src/pages/Intro/style.ts
- shared/toks-components/src/components/ToksHeader/index.tsx
- shared/toks-components/src/constants/env.ts
- shared/toks-components/src/constants/index.ts
1. 로그인 이모지 변경 
2. login 페이지 배경 이미지 변경
3. 헤더 높이 env로 추가
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/toks-components, login): 로그인 이모지 변경 / login 페이지 배경 이미지 변경

- services/quiz/src/pages/StudyDetailPage/components/StudyInfo/index.tsx
- services/quiz/src/pages/StudyDetailPage/components/StudyInfo/style.ts
- services/quiz/src/pages/StudyDetailPage/components/StudyProgress/index.tsx
- services/quiz/src/pages/StudyDetailPage/components/StudyProgress/style.ts
- services/quiz/src/pages/StudyDetailPage/index.tsx
- services/quiz/src/pages/StudyDetailPage/models/studyInfo.ts
- progress step, startedAt, endedAt을 props로 받아서 표현합니다.
- 크기는 530 x 200 고정으로 만들었슴다
- Start, Finish글자는 디자인 변경이 이루어져야 해서 body03으로 대체 하였습니다
- 스텝 별 이미지 추출이 지연돼서... 임시로 빨주노초파보 의 색깔 이미지로 대체하였습니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): 프로그레스바 구현

- services/quiz/src/pages/StudyDetailPage/components/QuizItem/index.tsx
- services/quiz/src/pages/StudyDetailPage/components/QuizList/index.tsx
- shared/toks-components/src/types/quiz.ts
- 똑스 확인하기 => vote
- 똑표하기 => vote
- 똑스 풀기 => solve
- Balloon은 표시하는 로직은 추가했으나 bottom방향 설정을 추가 작업 해야합니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): 내가 만든 퀴즈 기능 추가, 퀴즈를 추가해 주세요 Balloon표시 추가

- shared/layout/src/components/Layout.tsx
- shared/toks-components/src/components/ToksHeader/index.tsx
- shared/toks-components/src/constants/env.ts
Header 크기 변경 및 ENV에 환경변수 추가
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/toks-components, @depromeet/layout): Header 크기 변경 및 ENV에 환경변수 추가

- services/quiz/src/pages/QuizCheckingPage/components/AnswerCheckList/index.tsx
- services/quiz/src/pages/QuizCheckingPage/index.tsx
- services/quiz/src/pages/QuizCheckingPage/remotes/sortingQuizAply.ts
- services/quiz/src/pages/QuizSolvingPage/components/QuizEditor/index.tsx
- services/quiz/src/pages/QuizVotingPage/components/VoteSubmitButton/index.tsx
- 똑스 종료 시 우수 답변으로 바로 페이지 변경이 안되는 점을 해결했습니다. 
- 중복 답안 제출, 중복 투표 시 에러처리 작업을 진행했습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): 똑스 종료시 우수 답변 렌더링 및 중복 답안제출, 투표 시 에러처리 

- services/onboarding/src/pages/CreateStudy/components/CreateStudyForm/index.tsx
- services/onboarding/src/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- shared/toks-components/src/components/DropDown/index.tsx
> refactor(onboarding): 스터디 생성 필수 값 이슈 체킹

- services/quiz/pages/create/index.tsx
- shared/toks-components/src/components/Editor/Editor.tsx
- shared/toks-components/src/components/Input/index.tsx
- shared/toks-components/src/components/Upload/index.tsx
- shared/toks-components/src/components/Upload/useFileDrop.ts
- shared/toks-components/src/components/Upload/utils.ts
- [Input 자동완성 입력 시, 흰 배경 나오는 이슈 해결](https://5gaeanmal.slack.com/archives/C04HVDY7LFJ/p1673078742911689)
- [기존 에디터 이슈 해결을 위한 markdown 포맷 적용](https://5gaeanmal.slack.com/archives/C04HVDY7LFJ/p1673083321679029)
- 파일 업로드 accepts 적용 안되는 이슈 해결
> refactor(@depromeet/toks-components, quiz): QA 진행

- shared/toks-components/src/components/GlobalStyle/index.tsx
- shared/toks-components/src/components/ToksHeader/index.tsx
- [스크롤바 양 옆 패딩값 처리](https://github.com/depromeet/toks-web/pull/172)
- [닉네임에 따라 헤더 유저정보 길이 가변으로 처리 ](https://5gaeanmal.slack.com/archives/C04HVDY7LFJ/p1673074880387219)
- [헤더 background color 설정](https://5gaeanmal.slack.com/archives/C04HVDY7LFJ/p1673074880387219)
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> refactor(@depromeet/toks-components): QA 진행 

- services/onboarding/src/pages/CreateComplete/components/StudyInfoBox/index.tsx
- services/onboarding/src/pages/CreateComplete/index.tsx
- services/onboarding/src/pages/CreateStudy/index.tsx
- services/quiz/src/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- services/quiz/src/pages/QuizCreatePage/index.tsx
- services/quiz/src/pages/StudyDetailPage/components/QuizList/index.tsx
- services/quiz/src/pages/StudyDetailPage/index.tsx
- shared/path/src/index.ts
- shared/toks-components/src/components/Input/index.tsx
- shared/toks-components/src/components/TimePicker/index.tsx
- shared/toks-components/src/components/Toast/index.tsx
- shared/toks-components/src/components/ToksHeader/index.tsx
- shared/toks-components/src/constants/env.ts
1. 인풋 에러 발생시 에러문구때문에 인풋 컴포넌트가 구겨지는 이슈 해결
2. useTimePicker 에러 상황 제어 로직 일부 수정
3. type 부정확한 부분 수정
4. 빠진 routing 동작 추가
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(onboarding, quiz, @depromeet/toks-components, @depromeet/path): QA 반영

- service/src/onboarding/pages/CreateStudy/components/CreateStudyForm/index.tsx
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- 정책 반영하여 스터디 생성시 시작일을 입력 안한 경우 종료일을 입력하지 못하게 막았습니다. 
- 스터디 종료일이 시작일과 같거나 시작일보다 빠른 경우 validate 처리 해두었습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(onboarding): 스터디 시작일, 종료일 validate 처리

- scripts/deploy.sh
- service/pages/404.tsx
- service/pages/index.tsx
- shared/path/src/index.ts
배포 스크립트 수정, 404 페이지, "/" path로 접근시 동작 제어
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(toks): 배포 스크립트 수정, 404 페이지, "/" path로 접근시 동작 제어

- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
- service/src/quiz/pages/QuizCreatePage/remotes/postImageUpload.ts
- service/src/quiz/pages/QuizCreatePage/remotes/postQuizCreate.ts
- service/src/quiz/pages/QuizCreatePage/types.ts
- 업로드 URL api => 퀴즈 생성 로직으로 변경했습니다.
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): 퀴즈생성 로직 변경

- service/src/home/pages/JoinStudy/components/JoinStudyBox/index.tsx
- service/src/home/pages/JoinStudy/remotes/study.ts
- service/src/home/pages/MyStudies/components/StudyList/index.tsx
- service/src/onboarding/pages/CreateComplete/components/StudyInfoBox/index.tsx
- service/src/quiz/common/components/QuizQuestion/index.tsx
- service/src/quiz/common/components/QuizQuestion/remotes/quiz.ts
- service/src/quiz/common/remotes/quizReply.ts
- service/src/quiz/constants/queryKeys.ts
- service/src/quiz/pages/QuizCheckingPage/components/AnswerCheckList/index.tsx
- service/src/quiz/pages/QuizCheckingPage/index.tsx
- service/src/quiz/pages/QuizCheckingPage/remotes/sortingQuizAply.ts
- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
- service/src/quiz/pages/QuizSolvingPage/components/QuizEditor/index.tsx
- service/src/quiz/pages/QuizSolvingPage/components/StudyPeerAnswer/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/MyAnswerViewer/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/PeerAnswerList/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/VoteSubmitButton/index.tsx
- service/src/quiz/pages/StudyDetailPage/components/QuizList/index.tsx
- service/src/quiz/pages/StudyDetailPage/components/RankingList/index.tsx
- service/src/quiz/pages/StudyDetailPage/components/StudyInfo/index.tsx
- service/src/quiz/pages/StudyDetailPage/components/StudyInfo/style.ts
- service/src/quiz/pages/StudyDetailPage/hooks/queries/quizList.ts
- service/src/quiz/pages/StudyDetailPage/hooks/queries/rankingList.ts
- service/src/quiz/pages/StudyDetailPage/hooks/queries/studyInfo.ts
- service/src/quiz/pages/StudyDetailPage/index.tsx
- service/src/quiz/pages/StudyDetailPage/remotes/quizList.ts
- service/src/quiz/pages/StudyDetailPage/remotes/rankingList.ts
- service/src/quiz/pages/StudyDetailPage/remotes/studyInfo.ts
- shared/utils/src/hooks/usePathParam.tsx
- shared/utils/src/index.ts
1. query key에 누락된 의존성 추가. (잘못된 캐싱, studyId별로 캐싱이 이루어져야 정상) 
2. 잘못된 type 수정. (path param은 필수요소. string이 아니라면 throw error)
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(toks): query key 의존성 빠트린 부분 추가, type 부정확한 부분 수정

- service/pages/index.tsx
- service/src/home/pages/MyStudies/components/StudyList/index.tsx
- service/src/login/pages/KakaoAuth/index.tsx
- service/src/login/pages/MyName/components/NickNameBox/index.tsx
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
- service/src/quiz/pages/StudyDetailPage/components/QuizList/index.tsx
- shared/layout/src/components/Layout.tsx
- shared/toks-components/src/components/Accordion/style.ts
> feat(toks): prefetch 추가, 토스트 로직 수정

- service/src/quiz/pages/QuizCreatePage/components/QuizCreateEditor/index.tsx
- service/src/quiz/pages/StudyDetailPage/components/QuizList/style.ts
- service/src/quiz/pages/StudyDetailPage/components/RankingList/style.ts
- service/src/quiz/pages/StudyDetailPage/index.tsx
- shared/toks-components/src/components/Toast/index.tsx
- shared/toks-components/src/components/ToksHeader/index.tsx
> feat(toks): header, Suspense fallback, 화면 scroll 영역, 일부 디자인 수정

- service/src/quiz/pages/QuizVotingPage/index.tsx
- shared/toks-components/src/components/ToksHeader/index.tsx
- 헤더 아바타(유저 이미지)가 눌리는 현상을 수정했습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/toks-components): 헤더 아바타 눌리는 현상 수정

- service/src/quiz/pages/QuizVotingPage/index.tsx
- vote페이지에서 navbar에 임의로 넘기던 studyId를 삭제하고 studyId 넘기는 부분을 수정했습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): vote 페이지 navbar 뒤로가기 연결

- service/src/quiz/pages/QuizCheckingPage/components/AnswerCheckList/index.tsx
- quiz/check에서 작성된 답안이 없는 경우 아래와 같이 화면이 렌더링되도록 처리했습니다.
> feat(quiz): quiz/check 답안 없는 경우 처리

- shared/toks-components/src/components/GlobalStyle/index.tsx
> feat(toks): 가로 스크롤 방지

- service/src/onboarding/pages/CreateStudy/components/CreateStudyForm/index.tsx
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- service/src/quiz/pages/QuizCreatePage/index.tsx
- shared/toks-components/src/components/InputChips/index.tsx
> feat(quiz): 퀴즈생성 너비 수정, 스터디 생성 chips 수정

- service/src/onboarding/pages/CreateStudy/constants.ts
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- service/src/quiz/pages/QuizCreatePage/components/QuizCreateEditor/index.tsx
- service/src/quiz/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- service/src/quiz/pages/QuizCreatePage/constants.ts
- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
- service/src/quiz/pages/QuizCreatePage/index.tsx
- service/src/quiz/pages/QuizCreatePage/types.ts
> feat(quiz): 생성 디폴트값 추가 

- service/src/login/pages/KakaoAuth/index.tsx
> feat(toks): home 바로 접근하면 login 이슈 생기는 부분 해결

- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
> fix(quiz): 퀴즈 생성 후 리다이렉트 이슈 체킹

- service/src/home/pages/MyStudies/components/StudyCard/index.tsx
- service/src/quiz/common/components/QuizNav/index.tsx
- service/src/quiz/pages/QuizCreatePage/components/QuizCreateEditor/index.tsx
- service/src/quiz/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- service/src/quiz/pages/QuizCreatePage/index.tsx
- shared/layout/src/components/Layout.tsx
- shared/layout/src/components/UserMenu.tsx
- shared/utils/src/hooks/useSafelyGetUser.tsx
> feat(toks): qa 반영

- service/src/home/pages/JoinStudy/components/JoinStudyBox/index.tsx
- service/src/onboarding/pages/CreateComplete/components/StudyInfoBox/index.tsx
- 이미 스터디에 참여하고 있는 경우 post 400에러가 떨어져 토스트 알람 처리했습니다. 
- 태그가 있는 경우만 height를 가지도록 처리했습니다. 
- create complete 페이지의 태그 색을 피그마를 반영하여 변경했습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(home, onboarding): 이미 스터디에 참여하고 있는 경우 에러메세지, tag 색 변경

- shared/toks-components/src/components/Editor/Editor.tsx
- shared/toks-components/src/components/InputChips/index.tsx
> fix(toks): editor 반환 타입변경 및 chips 자동완성 삭제

- packages/http/src/http.ts
- service/pages/_app.tsx
- service/pages/_document.tsx
- service/src/components/Error.tsx
- service/src/home/pages/MyStudies/components/StudyCard/index.tsx
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- shared/layout/src/components/Layout.tsx
- shared/layout/src/components/UserMenu.tsx
- shared/toks-components/src/components/ToksHeader/index.tsx
> feat(toks):og, 에러 페이지, qa 대응

- service/src/login/pages/MyName/index.tsx
- service/src/quiz/common/components/QuizQuestion/index.tsx
- service/src/quiz/common/components/QuizQuestion/models/quiz.ts
- service/src/quiz/common/components/QuizQuestion/style.ts
- service/src/quiz/pages/QuizCheckingPage/components/AnswerCheckItem/index.tsx
- service/src/quiz/pages/QuizCheckingPage/components/AnswerCheckItem/style.ts
- service/src/quiz/pages/QuizCheckingPage/components/AnswerCheckList/index.tsx
- service/src/quiz/pages/QuizCheckingPage/components/AnswerCheckList/style.ts
- service/src/quiz/pages/QuizCheckingPage/components/EmptyAnswer/index.tsx
- service/src/quiz/pages/QuizCheckingPage/components/EmptyAnswer/style.ts
- service/src/quiz/pages/QuizCheckingPage/index.tsx
- service/src/quiz/pages/QuizSolvingPage/components/StudyPeerAnswer/style.ts
- service/src/quiz/pages/QuizVotingPage/components/PeerAnswerItem/index.tsx
- shared/toks-components/src/components/ToastViewer/ToastViewer.tsx
- shared/toks-components/src/constants/emoji.ts
- quiz/check 페이지에서 답안 넘어오지 않는 현상을 수정했습니다. 
- 답안이 없는 경우 피그마 반영하여 디자인 수정했습니다. 
- 기타 세부적인 디자인 사항들도 피그마 확인하며 수정했습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(login, quiz, @depromeet/toks-components): quiz/check 에서 답안 넘어오지 않는 현상 수정, 디자인 qa

- README.md
사진 수정함
내용도 같이 수정
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(readme): 사진과 내용 수정

- packages/http/src/http.ts
> feat(toks): error response 변형 방식 변경 / structuredClone 삭제

- service/src/login/pages/MyName/remote/nickName.ts
> feat(toks): 로그인 후 타이밍 이슈로 비회원 처리 되는 경우 처리

- service/src/quiz/pages/StudyDetailPage/components/QuizItem/index.tsx
- shared/toks-components/src/components/GlobalStyle/index.tsx
- [드롭다운 r깨지는 현상](https://5gaeanmal.slack.com/archives/C04HVDY7LFJ/p1673487658352729)
- [아직 안푼사람 없으면 글자 가리기](https://5gaeanmal.slack.com/archives/C04HVDY7LFJ/p1673358657896509)
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz, @depromeet/toks-components): 퀴즈 안푼사람 글자 visible로직 추가, 드롭다운 overflow hidden 추가

- service/src/quiz/pages/QuizCreatePage/remotes/postImageUpload.ts
> feat(toks): 파일 업로드 로직 변경

- service/src/quiz/pages/QuizSolvingPage/components/QuizEditor/index.tsx
- editor answer에 trim 적용
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): editor answer에 trim 적용

- service/src/quiz/pages/QuizVotingPage/components/MyAnswerViewer/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/PeerAnswerList/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/PeerAnswerList/style.ts
- service/src/quiz/pages/QuizVotingPage/index.tsx
- quiz 출제자 플로우를 추가했습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): 퀴즈 출제자 플로우 추가

- service/src/quiz/pages/StudyDetailPage/components/QuizItem/index.tsx
- shared/toks-components/src/components/UserAvatar/index.tsx
> feat(toks): 단일 아바타 툴팁 안뜨는 이슈

- packages/theme/src/colors.ts
- service/src/home/pages/MyStudies/components/StudyCard/index.tsx
- shared/toks-components/src/utils/quiz.ts
- 디자인 토큰 primary_opacity
- 똑스대장님이 퀴즈 추가 문구 -> 새로운 퀴즈가 추가되었어요 로 변경
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@depromeet/theme, home): 디자인 토큰 추가, 스터디 카드 문구 수정

- packages/http/src/http.ts
- service/src/login/pages/KakaoAuth/index.tsx
- service/src/login/pages/MyName/components/NickNameBox/index.tsx
> feat(toks): 로그인 페이지로 떨어질때 redirectUrl 물고 가도록 수정

- service/pages/_app.tsx
- favicon 추가
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(toks): favicon 추가

- service/src/login/pages/MyName/components/NickNameBox/index.tsx
> feat(toks): 닉네임 설정 후 default name 다시 불러오도록 수정

- service/src/login/pages/Intro/components/Banner/index.tsx
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
> feat(toks): 불필요한 toast option 제거

- service/src/quiz/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- shared/toks-components/src/components/Upload/index.tsx
- shared/toks-components/src/components/Upload/useFileDrop.ts
> feat(@depromeet/toks-components): useFileDrop에 파일 3개로 제한 기능 구현

- service/src/quiz/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- service/src/quiz/pages/QuizCreatePage/index.tsx
> feat(toks): qa

- service/src/home/pages/MyStudies/components/StudyCard/index.tsx
- service/src/home/pages/MyStudies/components/StudyList/index.tsx
- service/src/home/pages/MyStudies/models/study.ts
- service/src/home/utils.ts
> feat(home): 시작 안된 스터디 안내 문구 추가

- service/src/quiz/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- 캘린더 인풋막기 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(quiz): 캘린더 인풋막기

- shared/toks-components/src/components/Editor/Editor.tsx
- shared/toks-components/src/components/ToastViewer/ToastViewer.tsx
> feat(toks): 에디터, 뷰어 수정

- service/src/quiz/common/components/QuizQuestion/style.ts
> feat(quiz): 똑스풀기 스타일 재구성

- service/src/onboarding/pages/CreateStudy/components/CreateStudyForm/index.tsx
> feat(onboarding): chips 최대값 추가

- service/src/quiz/pages/QuizVotingPage/components/MyAnswerViewer/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/PeerAnswerItem/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/PeerAnswerList/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/PeerAnswerList/style.ts
- service/src/quiz/pages/QuizVotingPage/components/VoteSubmitButton/index.tsx
- shared/toks-components/src/components/Button/index.tsx
- shared/toks-components/src/components/ToastViewer/ToastViewer.tsx
> feat(toks): 버튼 disable값 변경 및 overflow 조정

- service/pages/_document.tsx
- shared/layout/src/components/Layout.tsx
> feat(toks): qs

- service/src/home/pages/JoinStudy/components/JoinStudyBox/index.tsx
- service/src/login/pages/MyName/components/NickNameBox/index.tsx
- service/src/onboarding/pages/CreateStudy/components/CreateStudyForm/index.tsx
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- service/src/quiz/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
- service/src/quiz/pages/QuizCreatePage/index.tsx
- service/src/quiz/pages/QuizSolvingPage/components/QuizEditor/index.tsx
- service/src/quiz/pages/QuizVotingPage/components/VoteSubmitButton/index.tsx
> feat(quiz,onboarding,home): post 요청 전부 isLoading disabled 처리

- shared/toks-components/src/components/Editor/Editor.tsx
> feat(toks): editor 코드블럭 스타일 적용

- shared/toks-components/src/components/ToastViewer/ToastViewer.tsx
> feat(toks): height 변경

- shared/toks-components/src/components/Editor/Editor.tsx
> feat(toks): editor 코드블럭 수정

- service/pages/_document.tsx
> feat(toks): og description 줄바꿈

- service/pages/_document.tsx
> fix(toks): og title

- service/next.config.js
- service/tsconfig.json
- ga, hotjar 적용 도중 config에러가 발생하여 수정했습니다. 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(toks): fix config error

- service/pages/_document.tsx
- shared/toks-components/src/components/Tooltip/TooltipContent.tsx
- shared/toks-components/src/components/Tooltip/TooltipPortal.tsx
- shared/toks-components/src/components/Tooltip/getTooltipPosition.ts
- shared/toks-components/src/components/Tooltip/index.tsx
- shared/toks-components/src/components/UserAvatar/index.tsx
- tooltip 개발했습니다.
- bottom 방향밖에 안돼요...ㅋ..ㅋ 
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(@deporomeet/toks-components): Tooltip 컴포넌트 prime-react 의존성 제거 및 리팩토링

- service/src/login/pages/Intro/components/Banner/index.tsx
- service/src/onboarding/pages/CreateComplete/components/StudyInfoBox/index.tsx
- shared/toks-components/src/components/Button/index.tsx
- button 컴포넌트에 link icon type을 추가했습니다. 
- button 내부에서 Text 설정을 해주고 있어 앞으로 사용하실 때 `<Button>버튼</Button>` 요렇게 바로 사용해주시면 됩니다.
> feat(@depromeet/toks-components, onboarding) : Button 컴포넌트에 icon type 추가 

- service/src/quiz/common/components/ModalContents/SubmitModal/index.tsx
- service/src/quiz/pages/QuizSolvingPage/components/QuizEditor/index.tsx
- shared/toks-components/src/components/Modal/index.tsx
- 디자인 레퍼런스: https://www.figma.com/file/b0TkpavIJ01efYPKv93MLl/Tok's-Design-System?node-id=3559%3A22185&t=5wGvd8lgUAiE517S-4
- 관련 슬랙 링크: 
- 모달 타입 "alert", "confirm"을 추가했습니다.
- onConfirm, onCancel을 활용해서 취소/확인 버튼을 관리해주세요!
> feat(@depromeet/toks-components, quiz): 모달 Confirm 타입 추가

- service/src/onboarding/pages/CreateStudy/components/CreateStudyForm/index.tsx
- service/src/onboarding/pages/CreateStudy/constants.ts
- service/src/onboarding/pages/CreateStudy/hooks/useCreateStudyForm.tsx
- service/src/quiz/common/components/QuizNav/index.tsx
- service/src/quiz/pages/QuizCreatePage/components/QuizCreateInputList/index.tsx
- service/src/quiz/pages/QuizCreatePage/hooks/useQuizCreate.ts
- service/src/quiz/pages/QuizCreatePage/index.tsx
- shared/toks-components/src/components/DropDown/index.tsx
- shared/toks-components/src/hooks/useForwardRef.ts
- shared/toks-components/src/types/study.ts
- Dropdown 1차 pr입니당 ^^ .. 
- Compound component로 만들었다가 날려먹어 Dropdown이 크게 기능적으로 확장될 일이 없을 것 같아 그냥 만들었습니다.. 
1. 컴포넌트를 사용하는 쪽에서 onChange 함수를 넘겨 selectItem을 받는 식으로 구현하는 방법 말고 다른 방법으로 값을 넘길 수는 없을까요,,?
2. 태그를 중첩하여 컴포넌트를 만든 경우 forwardRef를 어디에 달아주어야 react-hook-form을 사용했을 때 값을 읽을 수 있을까요..?
- 디자인 레퍼런스: 
- gray080은 선택된 요소, hover된 요소는 gray070 으로 background 설정했습니다. (hover가 우선순위 더 높음. )
> feat(@depromeet/toks-components): Dropdown 컴포넌트 Primereact 제거

- service/src/home/pages/MyStudies/components/StudyCard/index.tsx
- lottie size를 변경했습니다. (svg 영역이 잡혀있기 때문에 .. )
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(home): lottie size 변경

- .github/workflows/releaseTag.yml
잘 됐으면 좋겠슴니다...
https://medium.com/prnd/github에서-release-tag-자동으로-만들어-주기-1분만에-설정-5c09a383fb08
상기 링크를 참고하여 파일을 추가합니다
- 디자인 레퍼런스: 
- 관련 슬랙 링크:
> feat(release/tag) : 릴리즈 태깅하는 action

- service/package.json
> feat(toks): 1.0.0 version up
